### PR TITLE
Fix: initial push calendar filter border and placement

### LINKED ISSUE #70: 59664- [Newsroom] Newsfeed- Divider is missing below Search and Calendar Filter
**Priority**: 3 - Medium
**Steps to Reproduce:** 
1. Open URL 
**Legacy newsroom page:**
Homepage: https://newsroom.accenture.com/
**Adobe Franklin migrated page:** 
Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/
2. Navigate to the newsfeed section
**Actual (Migrated Page):** Search and Calendar Filter is in box 
image

**Expected(Legacy Newsroom Page):** Divider below the Search and Calendar Filter
image

Note: Issue exists in Small and Extra small devices.

Azdo Link-https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59664
cc: @ravkiran @amol-anand @raymond-pogi

### LINKED ISSUE #80: 59884- [Newsroom] Newsfeed- Calendar Filter is not visible when no search result found in small devices
Priority: 2 - High

**Steps to Reproduce:**
1. Open URL 
**Legacy newsroom page:**
Homepage: https://newsroom.accenture.com/
**Adobe Franklin migrated page:** 
Homepage: https://main--accenture-newsroom--hlxsites.hlx.live/

2. Open dev tool
3. View in small device
4. Select date range 

**Actual (Migrated Page):** Calendar Filter is not visible when no search result found
image

**Expected (Legacy Newsroom Page):** Calendar Filter should be visible when no search result found
image

| Device | iPad 5th | | Browser | Tablet_safari | | Operating System | iOS 15.0 | | Resolution | 1536 x 2048 px | | Screen size | 9.7 in - 5.8 x 7.8 in | | Viewport | 768 x 954 px | | Aspect Ratio | 4 : 3 |

Azdo Link- https://dev.azure.com/accenturecio26/WebContentDigAssetMgmt_PR1093/_workitems/edit/59884
cc: @ravkiran @amol-anand @raymond-pogi

### PR DESCRIPTION
**Pull request by zozo-j**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #70 
Fix #80 

Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/
- After: https://59884-calendar-filter2--accenture-newsroom--hlxsites.hlx.page/

### CODE REVIEW

**Comment by ravkiran** [comment]
@zozo-j this change is breaking the category pages https://59884-calendar-filter2--accenture-newsroom--hlxsites.hlx.page/subjects/technology

image

The border box for search/filter is explicitly added to make this similar to the category pages 

image

Can you please check with the business, if we can have home page and category pages to have the same box?

**Review by ravkiran — CHANGES_REQUESTED** [review]
please see my earlier comment

**Comment by zozo-j** [comment]
Hello @ravkiran , I'm sorry I overlooked the other pages where it was also affecting the view. If it's the look in category pages, I can just isolate my update to the homepage so that the category pages won't get affected, if it's fine. :)

**Comment by ravkiran** [comment]
@zozo-j did you check with business on

> Can you please check with the business, if we can have home page and category pages to have the same box?

**Pull request closed without merging**
